version: '3'

services:
  webapp:
    build: webapp
    ports:
      - 8501:8501
    depends_on:
      - worker
    volumes:
        - ./storage:/storage
  worker:
    build: worker
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage
